export const AppErrorCodes = {
  SUPABASE_USER_NOT_FOUND: "SUPABASE_USER_NOT_FOUND",
  APP_USER_NOT_FOUND: "APP_USER_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  USER_PERMISSION_DENIED_ERROR: "USER_PERMISSION_DENIED_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SUPABASE_CONNECTION_ERROR: "SUPABASE_CONNECTION_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
